### ISSUE TITLE
Items not marked as collected on interactive map

### ISSUE THREAD

**Issue by FBroy** [codengine/SOTFEdit#31]
Some items are marked as not collected (red) on the interactive map, even though they are collected in-game. (even after saving and reloading the save in SOTFEdit)

A few items which I can already confirm are affected, are:
- Laptop
- Rebreather
- Modern Axe
- Flashlight Attachment
- Ancient Armor

There may be more, but these are the ones I can see at first glance. If you need any more information, please let me know.

**Comment by codengine** [comment]
Could you attach one of the affected savegames so that I can have a look?

**Comment by FBroy** [comment]
[1606965940.zip](https://github.com/codengine/SOTFEdit/files/14664096/1606965940.zip)

This is my most recent save I have.
This is a multiplayer save, in case this matters.

Small example:
I have the rebreather and collected everything in cave C (the shovel cave), but yet the rebreather is shown in red and the laptop and Flashlight attachment are still shown on the map when selecting to show only uncollected items.
![image](https://github.com/codengine/SOTFEdit/assets/59142692/e3ea2da0-6359-4611-8638-34608b855bde)

**Comment by codengine** [comment]
I found the issue. Items that are currently equipped technically don't appear as "in inventory", so I'm going to have to find a workaround for that. Thanks for the report, I will call back when it is fixed!

**Comment by codengine** [comment]
Fixed in this release: https://github.com/codengine/SOTFEdit/releases/tag/v0.12.3

**Comment by FBroy** [comment]
Thanks for the quick patch! I'm currently testing everything and there still seem to be some edge cases.

- If armor/clothing is equipped, it is shown as not collected on the map. (I tested this with unequipping the ancient armor in the save above, which removed it from the interactive map)
- Laptops are still shown on the interactive map, even though these were already collected. In this save file, laptop 1 and laptop 2 were already collected.
- Weapon attachments, such as the flashlight for the pistol are shown as not collected on the map when equipped on a weapon. When dismantling it from the pistol in the save above, it is removed from the map.

The rest is working as expected from the patch.

**Comment by codengine** [comment]
Dang... I was too quick and it was late :P Gonna have a second look.

**Comment by codengine** [comment]
Please have a look at this build. It should resolve the issue with equipped cloths and weapon mods.
[SOTFEdit-f5a98877.zip](https://github.com/codengine/SOTFEdit/files/14738644/SOTFEdit-f5a98877.zip)

**Comment by FBroy** [comment]
After a quick initial test, the clothing and weapon attachments part seems to be fixed. However, now the clothing worn by Kelvin and Virginia is shown on the map as not collected. (Priest outfit for Kelvin and Camouflage outfit for Virginia in this save)

Also, the laptop part still persists. Not sure if you cannot change that at all, since you technically do not "take" the laptop, but just gain the information on it. I could open up another issue for this?

**Comment by codengine** [comment]
> After a quick initial test, the clothing and weapon attachments part seems to be fixed. However, now the clothing worn by Kelvin and Virginia is shown on the map as not collected. (Priest outfit for Kelvin and Camouflage outfit for Virginia in this save)
> 
> Also, the laptop part still persists. Not sure if you cannot change that at all, since you technically do not "take" the laptop, but just gain the information on it. I could open up another issue for this?

The laptop is a World Object State I think which is listed here:
![grafik](https://github.com/codengine/SOTFEdit/assets/498798/fdc9c830-8af0-462a-b332-dc764a81d0ad)

But I have no Savegame where every Laptop has been collected, so its kind of hard to research it.

For the outfit, "technically" you don't have it in your inventory. Also it is less of a outfit than more a "flag" for the followers - they do not really own the items. I'd leave it as it is for the follower items.

**Comment by FBroy** [comment]
Then that solves everything related to this issue! Thanks for taking care of it!
